clean:
	./gradlew clean

build:
	./gradlew clean build

install-dist:
	./gradlew clean installDist

lint:
	./gradlew checkstyleMain checkstyleTest

test:
	./gradlew test

report:
	./gradlew jacocoTestReport


.PHONY: build clean lint config test



